module.exports = {
  TIMEZONE: 'Asia/Seoul',
  MIN_VALID_AMOUNT: 1,
  RULE_STATUS: {
    INVALID_DATA: 'INVALID_DATA',
    CALCULATION_UNAVAILABLE: 'CALCULATION_UNAVAILABLE',
    INSUFFICIENT_HISTORY: 'INSUFFICIENT_HISTORY',
    DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  },
  AI_REQUIREMENTS: {
    LOOKBACK_DAYS: 90,
    MIN_HISTORY_DAYS: 1,
    MIN_APPROVED_TRANSACTIONS: 1,
  },
  RAPID_PAYMENT: {
    WINDOW_MINUTES: 10,
  },
  NEW_CATEGORY: {
    UNKNOWN_CATEGORY: '미분류',
  },
  DAILY_SPEND_SPIKE: {
    LOOKBACK_DAYS: 7,
  },
};